### PR TITLE
[WIN32-MingW Demo] TickType_t width is defined based on compiler type.(32bit/64bit)

### PR DESCRIPTION
**Pull request by watsk**
[WIN32-MingW Demo] TickType_t width is defined based on compiler type.(32bit/64bit)

Description
-----------

32bit `TickType_t` is used if compiler is MinGW32. 64bit `TickType_t` is used if compiler is MinGW64.

[Reason of change]
Before this change, 32bit `TickType_t` was always used in MinGW demo. It was inefficient for 64bit compiler. In addition, MinGW64 reported warnings for the cast operation between `TickType_t` and `void *` pointer because of different width. 64bit `TickType_t` should be used instead of 32bit if compiler is 64bit.

[Additional change]
Even if 64bit `TickType_t` is used, MinGW64 still reported warnings for the cast operation between 32bit variable and pointer type. To solve that, `uint32_t` has been replaced by `UBaseType_t` in some functions and `%u` has been replaced by `%llu` in `printf()`.

[Related forum topic]
This PR is derived by the following topic in the forum.
[64bit application on FreeRTOS windows port](https://forums.freertos.org/t/64bit-application-on-freertos-windows-port/19110)

[Limitation]
There are still same warnings in TraceRecorder module because 32bit variables are used as address there. They cannot be modified because TraceRecorder is out of FreeRTOS.

Test Steps
-----------

1. Build WIN32-MingW Demo by MinGW64 on **Debug** configuration and on **Debug_CodeCoverage** configuration.
2. Confirm there is no warning for the cast operation. (Except for TraceRecorder)
3. Run executable on both configurations.
4. Confirm they are running successfully.
5. Confirm code coverage is kept after change.

6. Those tests are performed by also MinGW32 as regression tests.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

If this PR is accepted, I will send another PR for similar changes for MSVC-Demo.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ActoryOu** [comment]
Hi @watsk,
Thanks for your contribution!
There is a CI failing in 32bit MingW. Could you please check if that matches your expectation?

Thank you.

**Comment by watsk** [comment]
@ActoryOu
Thank you for telling me about about build failure.
I found that `FreeRTOS/Source` submodule(FreeRTOS-kernel) is too old and it makes build failure.
This PR depends on the recent FreeRTOS-kernel update. (FreeRTOS-kernel [#1011](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1011))
I was testing this PR on the latest FreeRTOS-kernel.

Can I update submodule in this PR?  Or should submodule be updated on another PR separately?

**Comment by ActoryOu** [comment]
> @ActoryOu Thank you for telling me about about build failure. I found that `FreeRTOS/Source` submodule(FreeRTOS-kernel) is too old and it makes build failure. This PR depends on the recent FreeRTOS-kernel update. (FreeRTOS-kernel [#1011](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1011)) I was testing this PR on the latest FreeRTOS-kernel.
> 
> Can I update submodule in this PR? Or should submodule be updated on another PR separately?

Hi @watsk,
Yes, if updating submodule is couple with your change, they should be put together in same PR. Feel free to update this PR with the change.

Thanks for your contribution!

**Comment by watsk** [comment]
@ActoryOu
Thank you for your kind explanation.
I updated FreeRTOS-kernel submodule to the latest revision. It is newer than the revision which I actually need but I thought the latest one is better.
I also sent one more change because I found that type modification should be applied to one more variable.
I'm sorry for that I have uploaded insufficient changes at first.

**Comment by watsk** [comment]
@ActoryOu
Thank you for merging main into this branch and running CI check.
CI check failed on "verify-manifest" step. Then, I modified manifest.yml.
I didn't know manifest.yml should be updated when submodule is updated.
Could you run CI check again?

**Comment by watsk** [comment]
@ActoryOu
I modified prefix of variables because I found my modification does not follow coding style guide.
I confirmed demo application is built and run successfully as "full demo Debug" and "blinky demo Debug" and "Debug_CodeCoverage" on both of MinGW32 and MinGW64.

**Review by aggarg — APPROVED** [review]

**Review by ActoryOu — APPROVED** [review]

**Comment by ActoryOu** [comment]
@watsk,
Sorry for late response. I was occurpied by other tasks for a few days.
Thanks for your contribution. It now looks good to me.

**Comment by watsk** [comment]
@aggarg, @ActoryOu 
Thank you for reviewing and correcting code to follow style guide.
I'm happy to know this PR has been accepted.

**Pull request merged**
