### PR TITLE
Remove redundant TCP includes in FreeRTOS CBMC proofs

### PR DESCRIPTION
**Pull request by moninom1**
Description
-----------

- Remove includes from FreeRTOS cbmc proofs which are not needed.
- Remove redundant  aws_freertos_tcp_verification_access_tcp_define.h file.
- Remove redundant  aws_freertos_ip_verification_access_ip_define.h file.

Test Steps
-----------
CBMC proofs

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kar-rahul-aws** [comment]
In addition to this we can also remove this file [aws_freertos_ip_verification_access_ip_define.h](https://github.com/FreeRTOS/FreeRTOS/blob/main/FreeRTOS/Test/CBMC/include/aws_freertos_ip_verification_access_ip_define.h), since this API `publicProcessIPPacket` is not getting used in the tests?

**Comment by kar-rahul-aws** [comment]
This folder https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Test/CBMC/windows can also be removed .

**Comment by moninom1** [comment]
Yeah seems like just empty files. Let me remove them as well. Thanks

**Comment by tony-josi-aws** [comment]
This folder https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Test/CBMC/windows can also be removed .

I believe files are required by the kernel MSVC port. And it is not available on the system we use to run CBMC. Hence, those dummy files were created.  I had to create similar ones for +TCP in this PR: https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/1113

**Review by tony-josi-aws — APPROVED** [review]

**Review by aggarg — APPROVED** [review]

**Pull request merged**
