### PR TITLE
Add T-HEAD CK802 porting

### PR DESCRIPTION
**Pull request by xiaoxiacui**
1. Add T-HEAD ck802 processor port code under FreeRTOS/Source/portable/CDK/
2. CDK is our Integerity Development Environment  for T-HEAD processsor

### CODE REVIEW

**Comment by yuhui-zheng** [comment]
https://github.com/FreeRTOS/FreeRTOS/pull/3 Previous conversation can be found here.

**Comment by yuhui-zheng** [comment]
Hi @xiaoxiacui,

I downloaded the source code and attempted to setup environment. At the first attempt, I wasn't able to install CDK (see below for details). Would be nice to get some help from you on this specific matter. I also have a couple of other comments in below.


* Unable to install CDK.
```FreeRTOS\Demo\T-HEAD_CB2201_CDK\readme.txt``` mentioned CDK can be downloaded at https://occ.t-head.cn/community/download_detail?spm=a2oza.cdk.0.0.413b180fZ5hVxQ&id=575997419775328256. I've tried both versions available (2.0.2 and 1.18.11), and both do not allow me to change installation destination. Screenshot attached, installation defaulted to D:/, and "change..." button did not work for me.   
Screen Shot 2020-01-02 at 5 07 30 PM

* system requirement?
It wasn't clear to me what is the minimum system requirement for your CDK, that I assumed mine would work. (Windows 10, running as virtual machine.) Confirmation would be appreciated. 

* Further resources?
The download page says more available after login. (Not that I needed, but just out of curiosity.) I could not register since it seems your site asks for a phone number in +86, and login with Alibaba cloud does not work... This is definitely not a blocker for this PR, just mentioning as courtesy. Since customers may run into the same. 


Let us know. Thank you.

**Comment by yuhui-zheng** [comment]
I realize I'm getting into too much details. Is there a general getting started guide for your env setup? 

More updates. 

--------------------------------
Once I worked around installation path issue, I got another issue with failed to unzip cdk-sdk.zip (as attached). 
Screen Shot 2020-01-02 at 5 44 19 PM

Proceed without resolving this issue compilation failed for me. Log attached, the first error is 
``` 'HOBBIT1_2_GIPO0_PORTCTL_REG' undeclared```

[RTOSDemo_thead_compile_log.txt](https://github.com/FreeRTOS/FreeRTOS/files/4017897/RTOSDemo_thead_compile_log.txt)

Thanks for any help.

**Comment by xiaoxiacui** [comment]
Hi  zheng :

Sorry to bring you into the trouble of CDK installation. 
- the firstion problem is caused by the default setup path "D:/csk", there is no D disk in your computer, hence, you can change the install path to C:/ to fix the issue.
- you need to unzip the install file first, then double click setup.exe to start installtion process. Because we use the inside unZip tool to uncompress other ZIP files. if the installer can't find the Unzip tools, it will prompt the issue. 

Hope above can help you !

Vincent

**Comment by yuhui-zheng** [comment]
About the unzip issue -- I unzipped cdk-windows-V2.0.2-20191212-1645.zip, and started installation with setup.exe. The error message is popped during installation (the very last stage). 

cdk_sdk.zip is under ```<drive>\C-Sky\CDK\CSKY\ProjectTemplates\``` and ```<drive>\C-Sky\``` is my install destination path. I tried to manually unzip it, which does not work. 

So -- 
* which zip tool your install wizard takes dependency on?
* anything I need to add to PATH?

Thanks.

**Comment by xiaoxiacui** [comment]
Can you try to uninstall all files you have installed, and then try my way again ?

 

I am not sure if there is any other potential issue during installation in this case … 

 

 

发件人: Yuhui.Zheng <notifications@github.com> 
发送时间: 2020年1月4日 2:08
收件人: FreeRTOS/FreeRTOS <FreeRTOS@noreply.github.com>
抄送: xiaoxiacui <xiaoxia_cui@c-sky.com>; Mention <mention@noreply.github.com>
主题: Re: [FreeRTOS/FreeRTOS] Add T-HEAD CK802 porting (#4)

 

About the unzip issue -- I unzipped cdk-windows-V2.0.2-20191212-1645.zip, and started installation with setup.exe. The error message is popped during installation (the very last stage).

cdk_sdk.zip is under <drive>\C-Sky\CDK\CSKY\ProjectTemplates\ and <drive>\C-Sky\ is my install destination path. I tried to manually unzip it, which does not work.

So --

*	which zip tool your install wizard takes dependency on?
*	anything I need to add to PATH?

Thanks.

**Comment by yuhui-zheng** [comment]
Per offline communication, SVN is synced with the exact content in this PR. https://sourceforge.net/p/freertos/code/2802/. The next sync from SVN to GitHub will pick it up. I'm closing this PR for now.

**Pull request closed without merging**
