### PR TITLE
Update submodules of CSDK libraries

### PR DESCRIPTION
**Pull request by yourslab**
Description
-----------

Allows us to test the latest versions of the submodules in CI

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cobusve — APPROVED** [review]

**Review by pavanmr94 — APPROVED** [review]

**Comment by yourslab** [comment]
Have a higher chance at winning at a slot machine in vegas than getting these cbmc checks to pass

**Pull request merged**
