### PR TITLE
Migrated RL78/IAR port to EWRL78v3+

### PR DESCRIPTION
**Pull request by felipe-iar**
# RL78/IAR port update to EWRL78v3+

Description
-----------
The RL78/IAR port was based on earlier technology based on the UBROF object format. More recent versions of the IAR Embedded Workbench for Renesas RL78 use the industry standard ELF, which had impact on the interrupt vectors as well as for section placements.

Test Steps
-----------
Described in the new `Demo/RL78_multiple_IAR/README.md`

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by n9wxu** [comment]
Please review and resolve the conflicts.

**Comment by felipe-iar** [comment]
__Some extra explanations for changing the affected files:__
- The `.s87` files were removed in favor of its counterparts `.s` files, which highlights the aspect they were migrated to the newer object standard.
- The files in `FreeRTOS/Demo/RL78_RL78G13_Promo_Board_IAR` were replaced by a README.md pointing to `FreeRTOS/Demo/RL78_multiple_IAR` which already includes the complete demo for the promotion board.
- The remaining headers were tweaked to work with the YRPBRL78G14 board, as described in the new `FreeRTOS/Demo/RL78_multiple_IAR/README.md` document.

Please advise.

**Review by felipe-iar — COMMENTED** [review]
__Some extra explanations for changing the affected files:__
- The `.s87` files were removed in favor of their counterparts `.s` files, which highlights the aspect they were migrated to the newer object standard.
- The files in `FreeRTOS/Demo/RL78_RL78G13_Promo_Board_IAR` were replaced by a README.md pointing to `FreeRTOS/Demo/RL78_multiple_IAR` which already includes the complete demo for the promotion board.
- The remaining headers were tweaked to work with the YRPBRL78G14 board, as described in the new `FreeRTOS/Demo/RL78_multiple_IAR/README.md` document.

**Review by felipe-iar — COMMENTED** [review]
Reviewed.

**Comment by felipe-iar** [comment]
- Renamed the `interrupt_vector.s` module to `FreeRTOS_asm_vectors.S` which belongs to the ignore list.
- Updated README.md to reflect these changes.

**Comment by felipe-iar** [comment]
- Added `interrupt_vector.s`  to the ignore list in the `core_checker.py` script.
- Done.

**Comment by felipe-iar** [comment]
Hi @n9wxu. Thanks for all the directions. Hopefully all sorted out from my end, otherwise please let me know.

**Comment by felipe-iar** [comment]
### Fixed previous errors reported by the CI
- __FreeRTOS Core Checks__: The previous headers were failing. Updated source files to the header described in the `FREERTOS_HEADER` variable from the `core_checker.py` script.
- __spell-check__: Added keywords (_itmc_ and _usclockhz_ which were previously used in the original demo to the `lexicon.txt`

cc: @n9wxu

**Review by RichardBarry — APPROVED** [review]

**Review by n9wxu — APPROVED** [review]

**Pull request merged**
