### PR TITLE
CORTEX_M0_FT32F072_KEIL demo code

### PR DESCRIPTION
**Pull request by FMD-AE**
Add CORTEX_M0_FT32F072_KEIL demo code
Description
-----------

FT32F072 is one of the 32-bit Microcontroller of Fremont Micro Device Corporation,We request to add demo code of the freeRTOS.
If you want to test ,may need a development board of FT32F072 Microcontroller.
Test Steps
-----------

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aggarg** [comment]
Please move this demo to this repo: https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos

**Comment by aggarg** [comment]
I moved it in this PR - https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos/pull/4

**Comment by aggarg** [comment]
Closing this PR.

**Comment by FmdAE** [comment]
Hello,May I ask you a question?
Why the demos can't be submited to the FreeRTOS/Demo，and what can I do for submiting  to the FreeRTOS/Demo.
Looking forward to your reply,thank you!

**Comment by aggarg** [comment]
This page documents the guidelines for submitting FreeRTOS ports and corresponding demos - https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/portable/ThirdParty/README.md

The community supported demos repo and the partner supported demos repo are submoduled in this repo. Therefore, anyone cloning this repo will get demos in those two repos too. Is there a specific reason you want to put this demo here?

Thanks.

**Comment by FmdAE** [comment]
Yes,It will be more convenient to find the demos of CORTEX_M0_FT32F072.
We are MCU Company,and expect our demos can be place in the official area just like ST or other hardware platforms.

Thanks.

**Comment by aggarg** [comment]
We recently rearranged our repos in three categories of FreeRTOS Ports and Demos based on who provides [technical support]( https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/portable/ThirdParty/README.md): FreeRTOS supported, partner supported, and community supported. 

* FreeRTOS Ports and Demos created and supported by the FreeRTOS team are in the main repo. These ports and demos follow the same pattern and have a documentation page describing how to build and use the demo on the FreeRTOS.org website. We also have the hardware so can provide technical support when needed. 
* FreeRTOS Ports and Demos that are actively supported by silicon partners, so FreeRTOS users can get device support from the partner, are in the partner supported repo. We can still provide generic support for these ports and demos, but not device specific support. 
* Finally, contributed FreeRTOS Ports and Demos for which we can’t make any assurance about a technical support are in the community supported repo. 

Note that ports and demos in all three categories are included (as submodules) if you clone the main FreeRTOS Git repo, and all three are also included if you download the distribution as a zip file from the FreeRTOS.org website.
If you feel it is more appropriate for your demo to be in the partner supported repo and you are willing to provide the technical support, then please do the following:
1. Add a README file as per the instructions [here ](https://github.com/FreeRTOS/FreeRTOS/blob/main/FreeRTOS/Demo/ThirdParty/Template/README.md#add-readme).
1. As you are not using [the standard demos/tests](https://github.com/FreeRTOS/FreeRTOS/blob/main/FreeRTOS/Demo/ThirdParty/Template/README.md), I’d suggest to also describe your demos in the same README file.
1. Raise a PR to merge this demo to the [Partner Supported Demos repository](https://github.com/FreeRTOS/FreeRTOS-Partner-Supported-Demos). 
1. Raise a PR to delete the demo from this repository.

Thanks.

**Pull request closed without merging**
