### PR TITLE
Add FreeRTOS_Plus_WolfSSL_FIPS_Ready_Windows_Simulator

### PR DESCRIPTION
**Pull request by TakayukiMatsuo**
Add FreeRTOS_Plus_WolfSSL_FIPS_Ready_Windows_Simulator

Description
-----------
This demo project is created to show how the wolfSSL-FIPS-Ready version works and how to use it to build with the demo application.

This demo project contains the latest wolfSSL-FIPS-Ready version (v4.5.0). Also, in this demo, the unused wolfSSL files for building the demo application have been removed.

Test Steps
-----------
Build RTOSDemo.exe with the solution file in the FreeRTOS-Plus/Demo/FreeRTOS_Plus_WolfSSLFIPS_Ready_Windows_Simulator and then run it with Debugger.

However, the demo application will fail for the first run. An error is expected at this point. Extra steps are required to build the application including wolfSSL-FIPS-Ready version.  Please refer the "How to build and run the Demo application" section in the FreeRTOS-Plus/Demo/FreeRTOS_Plus_WolfSSL_FIPS_Ready_Windows_Simulator/README_wolfSSL_FIPS_ready.md. 

Related Issue
-----------
None

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cobusve** [comment]
Hi TakayukiMatsuo, we pushed some fixes to your branch yesterday but they seem to have been overwritten since? One of the things we fixed is that your commit is deleting this header file which seems to be incorrect.
 FreeRTOS/FreeRTOS/Demo/CORTEX_MPU_M7_NUCLEO_H743ZI2_GCC_IAR_Keil/ST_Code/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sd_ex.h

We would like to do a FreeRTOS release shortly and we need to get this resolved ASAP or it will not make it into the release.

**Review by cobusve — CHANGES_REQUESTED** [review]
ST_Code/Drivers/STM32H7xx_HAL_Driver/Inc/stm32h7xx_hal_sd_ex.h should not be deleted as part of this PR

Changes we made to version numbers and spelling errors have also been reverted, we need these to merge.

**Comment by TakayukiMatsuo** [comment]
I'm very sorry to trouble you. Should I add the missing header file to this repository?

**Comment by cobusve** [comment]
There is a lot of overlap between this PR and #303 it seems. I am going to merge that one and then come back to this one to see what is still outstanding. Since #303 also adds this we may be able to just close this one.

**Comment by cobusve** [comment]
@TakayukiMatsuo can you please take a look at this one now that #303 has been merged. We have a number of conflicts that need resolution on this one.

**Comment by TakayukiMatsuo** [comment]
Merging #303 made this PR(#214) unnecessary. I confirmed the FIPS-Ready demo is merged and works. Hence, let me close this PR. Thank you for your help.

**Comment by cobusve** [comment]
It is great to hear that the other PR has included this and is working fine. I am closing this one.

**Pull request closed without merging**
