### PR TITLE
Cortex m0 ft32 f072 keil

### PR DESCRIPTION
**Pull request by FmdAE**
Add the source file to the ignore list.
modified:   .github/scripts/core_checker.py

This directory contains an FT32F072XX demo project (ARM compiler V6.16) for FT32F072XX StarterKit board equipped with FT32F072XX microcontroller (128 KB Flash and 8 KB SRAM or 128 KB Flash and 24 KB SRAM).

The project comes with two different demos. One is standard demo tasks and the other is normal demo.

See the readme.md for detail.

### CODE REVIEW

**Comment by FmdAE** [comment]
Hi,
May I ask you a question?
Just as you say,how to add the file to the ignore list.
I thought change the file .github/scripts/core_checker.py is the way to add the file to the ignore list.
Thanks!



Best regards,
shenghui li     李圣辉
-----------------------------------
辉芒微电子（深圳）股份有限公司
Fremont Micro Devices (Shenzhen) Corporation 
Tel: (86 755) 8611 7811x1630
Fax: (86 755) 8611 7810
www.fremontmicro.com
Unit 1611, 16/F, Changhong Building,
Ke-Ji Nan 12 Road, Nanshan District,
Shenzhen, PRC,  P.C. 518057

 
From: Gaurav-Aggarwal-AWS
Date: 2022-02-18 14:59
To: FreeRTOS/FreeRTOS
CC: FmdAE; Author
Subject: Re: [FreeRTOS/FreeRTOS] Cortex m0 ft32 f072 keil (PR #796)
Also, then you'll not to change .github/scripts/core_checker.py.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by FmdAE** [comment]
Hi,
Thank you for your reply, 
I want our DEMO can be show at the FreeRTOS\FreeRTOS\Demo. I have work for this  three months ago, and you advised me that do the following:
Add a README file as per the instructions here .
As you are not using the standard demos/tests, I’d suggest to also describe your demos in the same README file.
Raise a PR to merge this demo to the Partner Supported Demos repository.
Raise a PR to delete the demo from this repository.
So I follow the tips, and raise the PR to the Partner Supported Demos repository,but no one review the PR.


Best regards,
shenghui li     李圣辉
-----------------------------------
辉芒微电子（深圳）股份有限公司
Fremont Micro Devices (Shenzhen) Corporation 
Tel: (86 755) 8611 7811x1630
Fax: (86 755) 8611 7810
www.fremontmicro.com
Unit 1611, 16/F, Changhong Building,
Ke-Ji Nan 12 Road, Nanshan District,
Shenzhen, PRC,  P.C. 518057

 
From: Gaurav-Aggarwal-AWS
Date: 2022-02-18 14:59
To: FreeRTOS/FreeRTOS
CC: FmdAE; Author
Subject: Re: [FreeRTOS/FreeRTOS] Cortex m0 ft32 f072 keil (PR #796)
As I mentioned on the previous PR, please contribute this project to https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos. Let me know if you would want me to move instead.
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aggarg** [comment]
Apologies for missing your earlier PR - https://github.com/FreeRTOS/FreeRTOS-Partner-Supported-Demos/pull/4

I have merged it now. I guess this one can be closed now?

**Comment by FmdAE** [comment]
Thank you!
I  have another question. You have said that  partner supported demo are included (as submodules) if I clone the main FreeRTOS Git repo, but I can not find my demo in the file.
I have just clone the main FreeRTOS Git repo, there is no demos. Is it in this path FreeRTOS\FreeRTOS\Demo\ThirdParty\Partner-Supported-Demos?
Looking forward to your reply. 



Best regards,
shenghui li     李圣辉
-----------------------------------
辉芒微电子（深圳）股份有限公司
Fremont Micro Devices (Shenzhen) Corporation 
Tel: (86 755) 8611 7811x1630
Fax: (86 755) 8611 7810
www.fremontmicro.com
Unit 1611, 16/F, Changhong Building,
Ke-Ji Nan 12 Road, Nanshan District,
Shenzhen, PRC,  P.C. 518057

 
From: Gaurav-Aggarwal-AWS
Date: 2022-02-18 18:26
To: FreeRTOS/FreeRTOS
CC: FmdAE; Author
Subject: Re: [FreeRTOS/FreeRTOS] Cortex m0 ft32 f072 keil (PR #796)
Apologies for missing your earlier PR - FreeRTOS/FreeRTOS-Partner-Supported-Demos#4
I have merged it now. I guess this one can be closed now?
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aggarg** [comment]
That is because submodule pointer needs to be updated. I have created this PR to update submodule pointer - https://github.com/FreeRTOS/FreeRTOS/pull/798

Once this PR is merged, you will see your demo when you clone FreeRTOS repo,

**Comment by FmdAE** [comment]
Thank you for your attention! I've got it. And I will  close this now.

**Pull request closed without merging**
