### PR TITLE
Modify the order of judgement when outputing formatted strings

### PR DESCRIPTION
**Pull request by zb1tree**
Description
-----------
A  contradictory judgement happened, kPRINTF_Minus was misspelled as kPRINT_POUND.
If format string was output with python style, the judgement should  takes precedence over the judgement of zero.

Test Steps
-----------
Describe the steps to reproduce.

Checklist:
----------
- [ ] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by archigup** [comment]
Hey, could you give some context for this PR?

What is the problem being solved?

**Comment by zb1tree** [comment]
> Hey, could you give some context for this PR?
> 
> What is the problem being solved?

Just complete the PR.

**Comment by aggarg** [comment]
The code is part of SDK from NXP and I do not think we should change it here. Please report it to NXP.

**Comment by aggarg** [comment]
Closing this PR. Please report this to NXP. Let us know if you need anything from us.

**Pull request closed without merging**
