### PR TITLE
RISC-V-Qemu-virt_GCC: correct configCPU_CLOCK_HZ define

### PR DESCRIPTION
**Pull request by wly3155**
Fix configCPU_CLOCK_HZ define for correct freeRTOS tick

Description
-----------
Qemu simulator runs at 10MHZ, defined by RISCV_ACLINT_DEFAULT_TIMEBASE_FREQ
at https://github.com/qemu/qemu/blob/master/include/hw/intc/riscv_aclint.h.
Thus correct configCPU_CLOCK_HZ to 10MHZ for correct freeRTOS tick.

Test Steps
-----------
Build Demo 'RISC-V-Qemu-virt_GCC' and run at Qemu riscv simulator.
Observes the log print frequency not match with mainQUEUE_SEND_FREQUENCY_MS
defined in ./Demo/RISC-V-Qemu-virt_GCC/main_blinky.c, whiel then after applied
this patch and re-build, it works as excepted.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rawalexe** [comment]
Thank you so much for your contribution, I'll let the team know about the PR and have one of the team members look at it as soon as possiible.

**Comment by aggarg** [comment]
The change looks good to me. Please apply the following patch to fix the CI failure:  [0001-Fix-CI-check.patch](https://github.com/FreeRTOS/FreeRTOS/files/12575701/0001-Fix-CI-check.patch)

**Review by aggarg — APPROVED** [review]

**Comment by aggarg** [comment]
@wly3155 Do you want to do that or do you want us to? If you want us to, you need to create PR from a branch other than main so that we can push to that branch.

**Comment by wly3155** [comment]
> @wly3155 Do you want to do that or do you want us to? If you want us to, you need to create PR from a branch other than main so that we can push to that branch.

Applied your patch and thanks a lot for your help

**Comment by aggarg** [comment]
Thanks. You also need to click the "Update Branch" button above. In future, please cut a separate branch in your fork and raise a PR from that branch.

**Comment by wly3155** [comment]
> Thanks. You also need to click the "Update Branch" button above. In future, please cut a separate branch in your fork and raise a PR from that branch.

thanks, I see and it does my first PR request

**Review by aggarg — APPROVED** [review]

**Review by kar-rahul-aws — APPROVED** [review]

**Pull request merged**
