### PR TITLE
Build: Fix Demo/RX100-RSK_Renesas_e2studio RTOS demo project build error

### PR DESCRIPTION
**Pull request by NoMaY-jp**
Description
-----------
This PR fixes Demo/RX100-RSK_Renesas_e2studio RTOS demo project build error.
There are no changes in the runtime functionality.

Test Steps
-----------
I did the following steps with e2 studio v1.1.1.10 and I used CC-RX V1.2.1. (According to .info file, the project was originally built with e2 studio v1.1.1.7 using CC-RX V1.2.1 (moreover, and very old source code of FreeRTOS perhaps 7 ~ 8 years ago). Unfortunately the project file format is too old to be updated by the e2 studio v7.8.0. Therefore remaking the project file is to be done in the future.)

(1) Run the following bat file in the Demo/RX100-RSK_Renesas_e2studio folder
CreateProjectDirectoryStructure.bat
(2) Comment out the following #error in the Demo/RX100-RSK_Renesas_e2studio/RTOSDemo/FreeRTOSConfig.h
#error Ensure CreateProjectDirectoryStructure.bat has been executed before building.  See comment immediately above.
(3) Import the project
(4) Clean all projects and start a build

But I don't have the evaluation board therefore I can't check the program which are built.
If this isn't acceptable for you, please let me know.

Related Issue
-----------
Update Renesas GCC compiler ports #135
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/135#issuecomment-680172086
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/135#issuecomment-679215454

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by NoMaY-jp** [comment]
The following zip file contains MOT, MAP and build.log files which were built using e2 studio 
v1.1.1.10, CC-RX V1.2.1 and code at https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/82fdc1c3ee4c5e8a1f10e2a2370c81088506e905 (Aug 29, 2020), FreeRTOS/FreeRTOS https://github.com/FreeRTOS/FreeRTOS/commit/bcd5dec6c46392c8ab30a091dda65379d46a2fb5 
(Aug 29, 2020) and the modified FreeRTOSConfig.h.

[RX100-RSK_Renesas_e2studio_Demo_MOT_e2_1_1_1_10_CCRX_1_2_1_20200831.zip](https://github.com/FreeRTOS/FreeRTOS/files/5151258/RX100-RSK_Renesas_e2studio_Demo_MOT_e2_1_1_1_10_CCRX_1_2_1_20200831.zip)

**Comment by NoMaY-jp** [comment]
I'm sorry that I'll update .project and .cproject so that later versions of e2 studio can be used.

**Comment by NoMaY-jp** [comment]
I updated project files for e2 studio v4.0.2.008 (the same as Demo/RX100_RX113-RSK_Renesas_e2studio RTOS demo project) and later versions.

The following files were copied from Demo/RX100_RX113-RSK_Renesas_e2studio then modified.

.project
.cproject
.info
makefile.init

The following files were copied from Demo/RX100_RX113-RSK_Renesas_e2studio but not modified.

cgprojectDatas.datas    <-- This file is empty.
Dependency_Scan_Preferences.prefs

The following files were removed because these aren't in Demo/RX100_RX113-RSK_Renesas_e2studio.

org.eclipse.cdt.managedbuilder.core.prefs
Project_Generation_Prefrences.prefs

-----------
The following zip file contains MOT, MAP and build.log files which were built using e2 studio v4.0.2.008, CC-RX V1.2.1 and code at https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/82fdc1c3ee4c5e8a1f10e2a2370c81088506e905 (Aug 29, 2020), FreeRTOS/FreeRTOS bcd5dec (Aug 29, 2020) and the modified FreeRTOSConfig.h. The MOT file is the same as which were built using e2 studio v1.1.1.10, CC-RX V1.2.1 and the same code and the same modified FreeRTOSConfig.h.

[RX100-RSK_Renesas_e2studio_Demo_MOT_e2_4_0_2_008_CCRX_1_2_1_20200901.zip](https://github.com/FreeRTOS/FreeRTOS/files/5157925/RX100-RSK_Renesas_e2studio_Demo_MOT_e2_4_0_2_008_CCRX_1_2_1_20200901.zip)

-----------
I did the following steps with e2 studio v4.0.2.008 and CC-RX V1.2.1.

(1) Run the following bat file in the Demo/RX100-RSK_Renesas_e2studio folder
CreateProjectDirectoryStructure.bat
(2) Comment out the following #error in the Demo/RX100-RSK_Renesas_e2studio/RTOSDemo/FreeRTOSConfig.h
#error Ensure CreateProjectDirectoryStructure.bat has been executed before building.  See comment immediately above.
(3) Import the project
(4) Clean all projects and start a build

Additionally I did the following steps with e2 studio v7.8.0 and CC-RX V3.02.

(11) Run the following bat file in the Demo/RX100-RSK_Renesas_e2studio folder
CreateProjectDirectoryStructure.bat
(12) Comment out the following #error in the Demo/RX100-RSK_Renesas_e2studio/RTOSDemo/FreeRTOSConfig.h
#error Ensure CreateProjectDirectoryStructure.bat has been executed before building.  See comment immediately above.
(13) Import the project
(14) Update legacy e2 studio projects
(15) Select toolchain type and toolchain version
(16) Clean all projects and start a build

But I don't have the evaluation board therefore I can't check the program which are built.
If this isn't acceptable for you, please let me know.

**Comment by NoMaY-jp** [comment]
I'm trying to remove CreateProjectDirectoryStructure.bat because I think that executing this batch file is inconvenient. But it will be another pull request because updating document of the following page will be necessary.

Low Power RTOS Demo - Renesas RX100
[https://www.freertos.org/RX100_RSK_Low_Power_Tick-less_RTOS_Demo.html](https://www.freertos.org/RX100_RSK_Low_Power_Tick-less_RTOS_Demo.html)
> Building and executing the demo application - e2studio
>
> Create the directory structure required by the Eclipse managed make system by executing the appropriate CreateProjectDirectoryStructure.bat batch file.
>
> If you are using e2studio with the Renesas compiler then execute FreeRTOS/Demo/RX100-RSK_Renesas/CreateProjectDirectoryStructure.bat.
>
> If you are using e2studio with the GCC compiler then execute FreeRTOS/Demo/RX100-RSK_GCC/CreateProjectDirectoryStructure.bat.

**Comment by NoMaY-jp** [comment]
Hello,

I may understand what happened in the past. Before the following issue and pull request in Amazon FreeRTOS repository, I guess that the project was able to be built. But only port.c was changed and FreeRTOSConfig.h was NOT changed at the time, so the project become unable to be built.

Missing _VECT in #pragma interrupt (Renesas RX100 series) #1006
https://github.com/aws/amazon-freertos/issues/1006

Add missing _VECT to #pragma interrupt in RX100/port.c #1013
https://github.com/aws/amazon-freertos/pull/1013

More information is here.

Compiler error when building FreeRTOS for Renesas RX113 (RX100) Demo
https://forums.freertos.org/t/compiler-error-when-building-freertos-for-renesas-rx113-rx100-demo/9529/8

And here.

Build: Fix Demo/RX100_RX113-RSK_Renesas_e2studio RTOS demo project build error #224
https://github.com/FreeRTOS/FreeRTOS/pull/224#issuecomment-687442987

Best regards,
NoMaY

**Review by mingyue86010 — APPROVED** [review]

**Review by cobusve — APPROVED** [review]

**Comment by VanNamDinh** [comment]
Dear @NoMaY-jp , @mingyue86010 

Thanks for your PR and review.  This is acceptable from us.

**Pull request merged**
