### PR TITLE
Build: Fix Demo/RX100_RX113-RSK_Renesas_e2studio RTOS demo project build error

### PR DESCRIPTION
**Pull request by NoMaY-jp**
Description
-----------
This PR fixes Demo/RX100_RX113-RSK_Renesas_e2studio RTOS demo project build error.
There are no changes in the runtime functionality.

Test Steps
-----------
I did the following steps on the e2 studio v7.8.0 and I used CC-RX V3.02.

(1) Import the project
(2) Update legacy e2 studio projects
(3) Select toolchain type and toolchain version
(4) Clean all projects and start a build

But I don't have the evaluation board therefore I can't check the program which are built.
If this isn't acceptable for you, please let me know.

Related Issue
-----------
Update Renesas GCC compiler ports #135
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/135#issuecomment-680172086
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/135#issuecomment-679215454

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by NoMaY-jp** [comment]
I did also the following steps with e2 studio v4.0.2.008 and I used CC-RX V2.3.0. (According to .info file, the project was originally built with the same tools: e2 studio v4.0.2.008 using CC-RX V2.3.0 (moreover, and old source code of FreeRTOS perhaps 4 ~ 5 years ago)).

(1) Import the project (compiler path is automatically changed)
(2) Clean all projects and start a build

But I don't have the evaluation board therefore I can't check the program which are built.
If this isn't acceptable for you, please let me know.

**Review by dachalco — APPROVED** [review]
@NoMaY-jp 

Thanks for catching this, and furthermore thanks for the details you provided. 
Following your 'Related Issues' links I noticed this issue is a consequence of [FreeRTOS-Kernel PR#135](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/135).

```c
#define	__VECT( x )		VECT ## x
#define	 _VECT( x )		__VECT( x )
```

`_VECT()` macro simply does preprocessor string concatentation via `##`. So `VECT(_CMT0_CMI0) = VECT_CMT0_CMI0`. 

This line in [port.c:299:](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/master/portable/Renesas/RX100/port.c#L299)
```c
#pragma interrupt ( prvTickISR( vect = _VECT( configTICK_VECTOR ), enable ) )
```
seems unnecessarily convoluted and appears to _vectorify_ a _vector_ in it's call to `VECT( configTICK_VECTOR )`.
I feel we ought to instead change port.c to not use `_VECT()` as case mentioned above and instead directly assign  `configTICK_VECTOR = VECT_CMT0_CMI0` as is currently the case in the demos (such as this one).


Nevertheless, I'm of the opinion that a broken-build-fix should not be gated on potential enhancements, so I've approved the PR.

**Comment by NoMaY-jp** [comment]
Hello @dachalco,

Thanks for your approving this PR and thanks for your comment.

Regarding to your comment, I agree with you. The better way is to modify port.c as you wrote:

port.c
```
#pragma interrupt ( prvTickISR( vect = configTICK_VECTOR, enable ) )
```

FreeRTOSConfig.h
```
#define configTICK_VECTOR VECT_CMT0_CMI0
```
Moreover, from view point of CC-RX user, the following definition is preferred:

FreeRTOSConfig.h
```
#define configTICK_VECTOR VECT( CMT0, CMI0 )
```
Of course, not only RX100 port but also other ports have to be modified. But, as of today, building RTOSDemo projects for Renesas RX MCUs using recent tools is difficult.

But, but, but, I (and probably Renesas) want another solution which has high compatibility with '[Renesas RX SmartConfigurator](https://www.renesas.com/products/software-tools/tools/solution-toolkit/smart-configurator.html)' code generating tool. For example (not only CC-RX port, but also GNURX port and ICCRX port (of course, GNURX and ICCRX need something else other than CC-RX's '#pragma interrupt')):

FreeRTOSConfig.h
```
No definition of 'configTICK_VECTOR'
```
port.c ('BSP_CFG_RTOS_SYSTEM_TIMER' is defined in one of header files generated by RX SmartConfigurator.)
```
#if ( configINCLUDE_PLATFORM_H_INSTEAD_OF_IODEFINE_H == 1 )

    #if ( BSP_CFG_RTOS_SYSTEM_TIMER == 0 )

        #pragma interrupt ( prvTickISR( vect = VECT( CMT0, CMI0 ), enable ) )

    #elif ( BSP_CFG_RTOS_SYSTEM_TIMER == 1 )

        #pragma interrupt ( prvTickISR( vect = VECT( CMT1, CMI1 ), enable ) )

    #elif ( BSP_CFG_RTOS_SYSTEM_TIMER == 2 )

        #pragma interrupt ( prvTickISR( vect = VECT( CMT2, CMI2 ), enable ) )

    #elif ( BSP_CFG_RTOS_SYSTEM_TIMER == 3 )

        #pragma interrupt ( prvTickISR( vect = VECT( CMT3, CMI3 ), enable ) )

    #endif

#else

    #pragma interrupt ( prvTickISR( vect = _VECT( configTICK_VECTOR ), enable ) )

    or 

    #pragma interrupt ( prvTickISR( vect = configTICK_VECTOR, enable ) )

#endf
```
Of course, there are other solutions to do so (for example, RX Smart Configurator changes the definition of configTICK_VECTOR in FreeRTOSConfig.h). But my (and probably Renesas's) new interest is here because it makes users to use FreeRTOS easier, even if a little.

Best regards,
NoMaY

**Comment by NoMaY-jp** [comment]
Hello @dachalco,

I may understand what happened in the past. Before the following issue and pull request in Amazon FreeRTOS repository, I guess that the project was able to be built. But only port.c was changed and FreeRTOSConfig.h was NOT changed at the time, so the project become unable to be built.

Missing _VECT in #pragma interrupt (Renesas RX100 series) #1006
https://github.com/aws/amazon-freertos/issues/1006

Add missing _VECT to #pragma interrupt in RX100/port.c #1013
https://github.com/aws/amazon-freertos/pull/1013

More information is here.

Compiler error when building FreeRTOS for Renesas RX113 (RX100) Demo
https://forums.freertos.org/t/compiler-error-when-building-freertos-for-renesas-rx113-rx100-demo/9529/8

Best regards,
NoMaY

**Pull request merged**
