### PR TITLE
Tcpip port msp432e401y

### PR DESCRIPTION
**Pull request by e-sr**
**Networkinterface driver for texas instruments msp432e401y**

Description

networkinterface.c implemented as described in [Porting FreeRTOS+TCP to a Different Microcontroller ](https://www.freertos.org/FreeRTOS-Plus/FreeRTOS_Plus_TCP/Embedded_Ethernet_Porting.html). 
The driver is a modified version of the  `EMACMSP432E.c` found in [SIMPLELINK-MSP432E4-SDK](https://www.ti.com/tool/download/SIMPLELINK-MSP432E4-SDK).
It is a zero copy driver, where  rx, tx and phy  events are handled directly in the interrupt routine.
I see the examples uses a deferred interrupt. Should I use the deferred interrupt approach?

TO DO/QUESTIONS  where i need some help by the maintainers:

- [ ] I see the examples uses a deferred interrupt. Should I use the deferred interrupt approach? working within the isr i had to define a function to signal the TCP stack for incoming frames. Is the [ implementation](https://github.com/e-sr/FreeRTOS/blob/92c949dd91452ce21626795dc241ca81f9e273d8/FreeRTOS-Plus/Source/FreeRTOS-Plus-TCP/portable/NetworkInterface/msp432e401y/Networkinterface.c#L1033-L1040) correct?

- [ ] i don't understand how i should notify the stack for link status changes, see SIGNAL_LINK_CHANGE macro.
  I have also some troubles understanding the usage from the stack of `xGetPhyLinkStatus`. It  seems that `xNetworkInterfaceOutput` is called before `xGetPhyLinkStatus` when the link is not up. Is that the correct behavior?
  see 05b38d7 commit 

- [ ] As described in the porting guide you should swap pointers when reciving frames. 
    ```c
        /* A pointer to the descriptor is stored at the front of the buffer, so
    swap these too. */
    *( ( NetworkBufferDescriptor_t ** )
       ( pxDescriptor->pucEthernetBuffer – ipBUFFER_PADDING ) ) = pxDescriptor;

    *( ( NetworkBufferDescriptor_t ** )
       ( pxDMARxDescriptor->pucEthernetBuffer – ipBUFFER_PADDING ) ) = pxDMARxDescriptor;

    ```
    Is this still necessary? 

- [x] implement the proposed [fix](https://github.com/FreeRTOS/FreeRTOS/issues/87#issuecomment-648058745) for the issue #87. Is this the way to go?
- [ ] instrument the code with the correct tracing macros at the correct place, see commit 7ebff9a 
- [ ] Fix license 

**Test Steps**

- [ ] provide a working example in another repo for the [SimpleLink™ Ethernet MSP432E401Y MCU Launchpad™](https://www.ti.com/tool/MSP-EXP432E401Y). Is there an example where i can start from?
- [ ] Complete README with istructions
- [ ] How can I test the driver? i am interested in this, and i will have some time to do the work. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by e-sr** [comment]
Can someone help?

**Comment by htibosch** [comment]
@e-sr : I just saw your PR, just by coincidence. I am sorry that I didn't notice it earlier.
What is the status of this project today? Are you still working on it?

In general, if you look for FreeRTOS support, the [FreeRTOS forum](https://forums.freertos.org) is a better place than Github. It has more readers and you get help more quickly.
Hein

**Comment by cobusve** [comment]
@e-sr ,  I have changed this PR to DRAFT status as it seems to still have some outstanding work. If you are still interested in getting this merged then please respond here and we can provide guidance to get this merged.

**Comment by e-sr** [comment]
Hi Iam still intersted to get the work done, i will have some time next month.

**Comment by AniruddhaKanhere** [comment]
Hello @e-sr, thank you for being a contributor to the FreeRTOS community. 
Can you please recreate this PR in the new FreeRTOS-Plus-TCP repository [here](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP).
The FreeRTOS+TCP source code does not reside in FreeRTOS/FreeRTOS (this) repository anymore.

Apologies for the inconvenience.

**Comment by AniruddhaKanhere** [comment]
Hello @e-sr,
another customer has created [a PR](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/193) in the FreeRTOS+TCP repository for the same port - it is actively being worked on.
If you want to test that out or to contribute to that PR, it would be great.

**Comment by cobusve** [comment]
It seems that the other PR is adding a functional driver for this interface now. I am going to close this PR in favor of the other one, if there is something in this one which is still of value and should be merged into the driver please open a different PR for that.

**Pull request closed without merging**
