### PR TITLE
Updated to Percepio Tracealyzer Recorder v4.4.0

### PR DESCRIPTION
**Pull request by eriktamlin**
Updated to Tracealyzer Recorder v4.4.0

Description
-----------
Updated to Tracealyzer Recorder v4.4.0.
Also added configuration support for FreeRTOS v10.4.1.

Test Steps
-----------
N/A

Related Issue
-----------
N/A

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by cobusve — APPROVED** [review]

**Comment by cobusve** [comment]
We would like to merge this PR in but it was created without granting update rights and it is our of date with master. Can you please rebase this on the master branch for us so that we can merge this in. 

If you could grant me access to the fork I could do it for you. My only other option is to push this to my own fork and re-create the PR from there, if I hear nothing I will commence doing that instead.

**Comment by eriktamlin** [comment]
Rebased to master.

Thank you!

**Comment by cobusve** [comment]
I think the easy way is when you create the PR to click the checkbox. "Allow edits ..." at the bottom. 

image

**Review by cobusve — APPROVED** [review]

**Pull request merged**
