### PR TITLE
Shakti board support to Freertos

### PR DESCRIPTION
**Pull request by nsathya123**
Add shakti board support to FreeRTOS
Description
-----------

Add a board support folder under FreeRTOS/Demo folder
Test Steps
-----------

na
Related Issue
-----------

na

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by snarayan123 — APPROVED** [review]

**Review by snarayan123 — DISMISSED** [review]

**Comment by nsathya123** [comment]
@cobusve File headers check is failing. what should be done here ?

**Comment by cobusve** [comment]
I can override headers that fail, I see you do have GPL in some of the files, we do not generally allow GPL licenses in this repository, we use the less restrictive MIT license to ensure that people can freely use the code without having legal obligations to reveal their source code.

Could you consider changing the license to MIT in the headers like init.c?

**Comment by snarayan123** [comment]
We will work locally and get back to you.

**Comment by dachalco** [comment]
@snarayan123

The header check output is stale and will update upon next commit -- check was updated since last commit.
The check's latest output would be more informative on how/when to omit files, but the latest version of the check won't be effective until next commit in this PR, so I've summarized below.


There's several mechanisms you can use to omit files from the check in your fork's `.github/scripts/core_checker.py`. For now, ignores can be specified with [regex patterns](https://github.com/FreeRTOS/FreeRTOS/blob/master/.github/scripts/core_checker.py#L249), file names, or file extensions. You can omit files as needed (ex. different licensing) by committing said changes in your fork:branch.

**Comment by aggarg** [comment]
Moving this to the community contributed demos - https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos/pull/2

**Comment by aggarg** [comment]
Closing this PR as this has been merged in the community supported demos - https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos/pull/2

**Pull request closed without merging**
