### PR TITLE
Resolve stdio and stream_buffer link errors in RX64M demo (#42)

### PR DESCRIPTION
**Pull request by befree68**
Resolve stdio and stream_buffer link errors in RX64M demo (#42)

Description
-----------
`.cproject`: Added stdio.h to standard library build. This is required because Common_Demo_Source\Minimal\MessageBufferDemo.c (and others) use `sprintf`.

`.project`: Included stream_buffer.c in the FreeRTOS source directory. This is required because Common_Demo_Source\Minimal\MessageBufferDemo.c uses numerous stream buffer functions such as `vStreamBufferDelete`.

Test Steps
-----------
See #42 for reproduction steps.
Tested by doing a git clone of this fork into a clean workspace, importing the project into Renesas E2 Studio IDE, and pressing "Build All". Verified that no errors occurred. Then loaded it onto the development board and verified that LED0 was blinky.

Related Issue
-----------
N/A

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yuhui-zheng** [comment]
Thank you for this PR. Will verify and circle back.

**Comment by NoMaY-jp** [comment]
I think that this pull request can be closed because the linker errors is solved by commit https://github.com/FreeRTOS/FreeRTOS/commit/1ae6eda77aa5665d50a889f814736121e7f9960e

**Comment by VanNamDinh** [comment]
Dear @NoMaY-jp , @mingyue86010 

I think we can close this PR because @NoMaY-jp submitted PR #245

**Review by mingyue86010 — APPROVED** [review]

**Comment by mingyue86010** [comment]
Closed this PR. The fixed is submitted in https://github.com/FreeRTOS/FreeRTOS/pull/245

**Pull request closed without merging**
