### PR TITLE
Update submodule pointers of third party demos

### PR DESCRIPTION
**Pull request by aggarg**
Description
-----------
Update submodule pointers of third party demos

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by muneebahmed10 — APPROVED** [review]

**Review by RichardBarry — APPROVED** [review]

**Comment by FmdAE** [comment]
Hi,This PR is merged. Then I find that third party demos can be found in github.But when I download or clone this repo, There is nothing in FreeRTOS\Demo\ThirdParty.

**Comment by aggarg** [comment]
Which command are you using to clone this repo? Can you try the following command:

```
git clone https://github.com/FreeRTOS/FreeRTOS.git --recurse-submodules
```

**Comment by FmdAE** [comment]
Yes, I have tried the following command:
git clone https://github.com/FreeRTOS/FreeRTOS.git --recurse-submodules
And I see the  LOG as follows, Is it because of poor Internet access.

Cloning into 'D:/WorkSpace/FMD/1111/6100 FreeRTOS/Test/FreeRTOS/FreeRTOS/Demo/ThirdParty/Community-Supported-Demos'...
fatal: unable to access 'https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos/': OpenSSL SSL_read: Connection was reset, errno 10054
Cloning into 'D:/WorkSpace/FMD/1111/6100 FreeRTOS/Test/FreeRTOS/FreeRTOS/Demo/ThirdParty/Partner-Supported-Demos'...
fatal: unable to access 'https://github.com/FreeRTOS/FreeRTOS-Partner-Supported-Demos/': OpenSSL SSL_read: Connection was reset, errno 10054

**Comment by aggarg** [comment]
That seems like a network issue. Are you able to access these links from the same machine?
* https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos/
* https://github.com/FreeRTOS/FreeRTOS-Partner-Supported-Demos/

**Comment by FmdAE** [comment]
Yes,I can access these links from the same machine.And I can clone it with the following command,
git clone git@github.com:FreeRTOS/FreeRTOS-Community-Supported-Demos.git
But I can not clone it with the following command,   
git clone  https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos.git

I think I may find out the reason. When I clone with SSH URLs. It still clone the submodulest with HTTPS URLs. I don't know why.
And as my HTTPS URLs Internet speed is very unstable, so the clone work  failed.

**Comment by aggarg** [comment]
Glad that it works for you.

**Comment by FmdAE** [comment]
Is there other way to download expect clone.
I click the Download ZIP,and it doesn't include the submodules.
Also I download from the https://www.freertos.org/, it doesn't inchude the submodules either.

**Comment by aggarg** [comment]
If you think that SSH link works for you, you can change HTTPS links to SSH links here an try: https://github.com/FreeRTOS/FreeRTOS/blob/main/.gitmodules#L57

**Comment by FmdAE** [comment]
Is that means I can pull requests to change this file?

**Comment by aggarg** [comment]
No. We do not put SSH links. I suggested that only because you said that HTTPS is not working and SSH will probably work for you.

**Comment by FmdAE** [comment]
And what can I do to try this,
Or can the demos put in the path https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo instead of thirdparty.
Is there any rules or requirement if I really need put in the path? Demos in the thirdparty is hard to clone and find for the developers.

**Comment by aggarg** [comment]
Demos in third party are not hard to clone and it has been working for everyone. The instructions on the top level [README ](https://github.com/FreeRTOS/FreeRTOS/blob/main/README.md)file tells to use the git clone with recurse-submodules. Is it possible for you to try with a better internet connection?

In addition, your demo will be available in the release zip (both from [GitHub Releases](https://github.com/FreeRTOS/FreeRTOS/releases)and from FreeRTOS.org website) when we create our next release.

**Pull request merged**
