### PR TITLE
Re-do #108 -- Percepio Tracealyzer Recorder v4.3.11

### PR DESCRIPTION
**Pull request by yuhui-zheng**
Description
-----------
It seems odd in https://github.com/FreeRTOS/FreeRTOS/pull/108 that we have lots of commits due to branch merge. (Prefer rebase over merge.) While I believe this PR and PR #108 are equivalent for the final results, I think it's better to have to-the-point commit only in PR. 

This is a draft PR to show the idea. 

What's in PR #108:
Screen Shot 2020-07-27 at 11 46 18 AM

What's in this PR:
Screen Shot 2020-07-27 at 11 47 01 AM

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by eriktamlin** [comment]
Should I close the old one?

**Comment by yuhui-zheng** [comment]
@eriktamlin  No worries, we'll take care of it. This is in queue, we should be able to pick one and close the other.

**Comment by mingyue86010** [comment]
The changes were accepted in this PR: https://github.com/FreeRTOS/FreeRTOS/pull/201
Also fixed the Tracealyzer demo build error.

**Comment by yuhui-zheng** [comment]
Closing this PR. Thank you @mingyue86010 .

**Pull request closed without merging**
