### PR TITLE
Fix issue in CORTEX_LM3S811_GCC Demo linkerscipt

### PR DESCRIPTION
**Pull request by mghicho**
The .text section is listed as *(.text) and results in build
error because there are some .text* sections that are automatically put
into flash later by linker and their LMA overlaps
with .data

Description
-----------

explained in description
Test Steps
-----------

To reproduce, go to the CORTEX_LM3S811_GCC demo  folder and build with gcc-arm-none-eabi.

Related Issue
-----------

n/a

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by RichardBarry** [comment]
Thanks for taking the time to submit this PR.  I would be grateful if you could let me know the GCC version you are using.

**Comment by mghicho** [comment]
Hi Richard,
I'm using :
arm-none-eabi-gcc (GNU Arm Embedded Toolchain 9-2020-q2-update) 9.3.1 20200408 (release)

**Review by mingyue86010 — APPROVED** [review]

**Review by cobusve — APPROVED** [review]

**Review by mingyue86010 — APPROVED** [review]

**Pull request merged**
