### PR TITLE
Xtensa Demos updated and moved to Partner-Supported submodules

### PR DESCRIPTION
**Pull request by ianstcdns**
Cadence/Xtensa: Move Tensilica demos to Partner-Supported-Demos submodule

Description
-----------
- Remove out-of-date demo code
- Add a README to this deprecated demos directory indicating where to find the latest Tensilica test code.

Test Steps
-----------
- Tested via various demo and stress tests as provided through the Partner-Supported-Demos submodule.
- Regression testing on many different LX7, LX8, and NX configurations.

Checklist:
----------

- [ x ] I have tested my changes. No regression in existing tests.
- [ x ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.

Related Issue
-----------
N/A

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ianstcdns** [comment]
@aggarg @RichardBarry

Submitting updated Xtensa port to FreeRTOS v11

I've created pull requests for Cadence's updated Xtensa FreeRTOS port and demo code.  As you recommended, we have moved it to the Partner-Supported-Ports and Partner-Supported-Demos submodules, removed out-of-date code from the higher-level repos, and left a couple of READMEs in the old locations indicating the new home for this code.

Thank you in advance for your help reviewing this upstream request.

**Comment by rawalexe** [comment]
Hello @ianstcdns ,
Thank you for your contribution, the PR to the community supported demos has been merged in, can you please update the pointer to the latest commit and then we ca have this merged in

**Comment by ianstcdns** [comment]
Thank you for the quick review and merge.  Shall I wait until the Partner-Supported-Ports submodule pointer is updated in FreeRTOS-Kernel, and pull that pointer update in to this PR along with the Partner-Supported-Demos submodule pointer, or would it be better to do that separately?

**Review by aggarg — APPROVED** [review]

**Comment by aggarg** [comment]
Please update the commit hash of partner supported demo here to fix the manifest check - https://github.com/FreeRTOS/FreeRTOS/blob/main/manifest.yml#L141.

**Comment by ianstcdns** [comment]
> Please update the commit hash of partner supported demo here to fix the manifest check - https://github.com/FreeRTOS/FreeRTOS/blob/main/manifest.yml#L141.

Updating commit hash for Source and Partner-Supported-Demos submodule updates.  Thanks for the pointer.

**Review by rawalexe — APPROVED** [review]

**Review by aggarg — APPROVED** [review]

**Pull request merged**
