### PR TITLE
Latest Percepio Tracealyzer Recorder v4.3.11

### PR DESCRIPTION
**Pull request by eriktamlin**
Latest Percepio Tracealyzer Recorder, v4.3.11

Description
-----------
The recorder in the repository is greatly outdated and doesn't compile with later FreeRTOS versions.
As part of Percepio's new release procedure we will be creating pull requests to keep the trace recorder in FreeRTOS-Plus up-to-date.

Test Steps
-----------
N/A

Related Issue
-----------
N/A

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice. Note that the terms of usage stated by Percepio is provided in the source files.

### CODE REVIEW

**Comment by eriktamlin** [comment]
This is the trace recorder you get when installing Tracealyzer v4.3.11.

**Comment by yuhui-zheng** [comment]
@eriktamlin The branch is out of sync due to the uncrustify PRs, and I do not seem to have permission to push to your branch for rebasing purpose. Would you prefer us replacing this PR with a new one on your behalf, or rebasing your fork branch by yourself? Let us know. And thank you for the contribution.

**Comment by eriktamlin** [comment]
I rebased the PR to upstream/master.
It says a lot of files have changed...?

**Comment by yuhui-zheng** [comment]
I believe branch merge caused some fraction. (Please see #169 the attached branch history snapshots, that may better explain.) I'll put down "approved" for now for this PR, since I believe the contents are the same. 

(Note for other reviewers -- We'll need to do a squash merge for this PR, if accept as-is.)

**Comment by eriktamlin** [comment]
Should I close the this one and we just go with [https://github.com/FreeRTOS/FreeRTOS/pull/169](your redo) instead?

**Comment by yuhui-zheng** [comment]
@eriktamlin  No worries, we'll take care of it. This is in queue, we should be able to pick one and close the other.

**Comment by mingyue86010** [comment]
The changes were accepted in this PR: https://github.com/FreeRTOS/FreeRTOS/pull/201
Also fixed the Tracealyzer demo build error.

**Comment by yuhui-zheng** [comment]
Closing this PR. Thank you @mingyue86010. 

If any pending discussion, let's move to #201.

**Pull request closed without merging**
