### PR TITLE
FreeRTOS+TCP : Adding a Network Interface for STM32H7

### PR DESCRIPTION
**Pull request by htibosch**
A Network Interface for STM32H7

Description
-----------
Adding a simple Network Interface for STM32H7. It was published earlier on the FreeRTOS forum by Thomas Kindler.
Now adding it to the FreeRTOS repo so it doesn't get lost and all users can have access to it.
It still needs some modifications to optimise it and handle the PHY more properly.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by htibosch** [comment]
About commit "Changed the order of initialisation":

In `xNetworkInterfaceInitialise()`: do not create a task before both the ETH and the PHY have been initialised.
Reason: the task will take over the ETH and the PHY, and poll for the Link Status.

**Comment by brendanhaines** [comment]
This doesn't build for me. Some names from STM32Fxx are used such as xETH which is not defined in the STM32Hxx NetworkInterface.c

**Comment by AniruddhaKanhere** [comment]
> This doesn't build for me. Some names from STM32Fxx are used such as xETH which is not defined in the STM32Hxx NetworkInterface.c

Hello Brendan,

This is not yet complete and cannot handle the PHY properly.
Still, @htibosch, can you can give him some pointers? it would be great.

Thanks,
Aniruddha

**Comment by htibosch** [comment]
All right, I did the following:

- Merge branch 'master' into [htibosch:STM32H7_network_interface](https://github.com/htibosch/FreeRTOS/tree/STM32H7_network_interface)
- Added the code that uses `phyHandling.c`
- Start making use of the ISR callbacks like `HAL_ETH_RxCpltCallback`
- Test compiled with `STM32H745xx` defined
- Committed and pushed the changes

Please see [this post](https://forums.freertos.org/t/freertos-tcp-for-stm32h7/7618/34) about the origin of this network interface.
@brendanhaines : you can also ask questions about the STM32Hxx driver in mentioned post.

**Comment by htibosch** [comment]
Closing this PR #48, because it will be replaced by a new rebased PR #79

**Pull request closed without merging**
